// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200110114317_InitialFestivalMigration")]
    partial class InitialFestivalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("Domain.Event.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("CleanUpTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PreparationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TicketCountPrediction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TicketPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Domain.Event.Festival", b =>
                {
                    b.Property<int>("FestivalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .HasColumnType("TEXT");

                    b.HasKey("FestivalId");

                    b.ToTable("Festivals");
                });

            modelBuilder.Entity("Domain.Event.FestivalEvent", b =>
                {
                    b.Property<int>("FestivalEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FestivalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIncludedInFestivalPass")
                        .HasColumnType("INTEGER");

                    b.HasKey("FestivalEventId");

                    b.HasIndex("EventId");

                    b.HasIndex("FestivalId");

                    b.ToTable("FestivalEvents");
                });

            modelBuilder.Entity("Domain.Event.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParticipantTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ParticipateBegin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ParticipateEnd")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ParticipantId");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantTypeId");

                    b.HasIndex("PersonId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Domain.Event.ParticipantType", b =>
                {
                    b.Property<int>("ParticipantTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixedSum")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GetsFixedSum")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GetsHourly")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HourlyWage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParticipantTypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("ParticipantTypeId");

                    b.ToTable("ParticipantTypes");
                });

            modelBuilder.Entity("Domain.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("VatSubjectNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Domain.Track_sets.Set", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("SetDuration")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetName")
                        .HasColumnType("TEXT");

                    b.HasKey("SetId");

                    b.HasIndex("EventId");

                    b.HasIndex("PersonId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("Domain.Track_sets.SetTrack", b =>
                {
                    b.Property<int>("SetTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ActualPlayTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PlannedPlayTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SetTrackId");

                    b.HasIndex("SetId");

                    b.HasIndex("TrackId");

                    b.ToTable("SetTracks");
                });

            modelBuilder.Entity("Domain.Track_sets.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinutePrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PopularityOutOfTen")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TimeSpan")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vibe")
                        .HasColumnType("TEXT");

                    b.HasKey("TrackId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("Domain.Track_sets.TrackPayRight", b =>
                {
                    b.Property<int>("TrackPayRightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayRightPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrackPayRightId");

                    b.HasIndex("PersonId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackPayRights");
                });

            modelBuilder.Entity("Domain.Venue.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentHourlyPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LenderPersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EquipmentId");

                    b.HasIndex("LenderPersonId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("Domain.Venue.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HourlyPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimplePrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VenueAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueName")
                        .HasColumnType("TEXT");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("Domain.Venue.VenueEquipment", b =>
                {
                    b.Property<int>("VenueEquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReturnAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VenueEquipmentId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("VenueId");

                    b.ToTable("VenueEquipments");
                });

            modelBuilder.Entity("Domain.Event.Event", b =>
                {
                    b.HasOne("Domain.Venue.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Event.FestivalEvent", b =>
                {
                    b.HasOne("Domain.Event.Event", "Event")
                        .WithMany("FestivalEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Event.Festival", "Festival")
                        .WithMany("FestivalEvents")
                        .HasForeignKey("FestivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Event.Participant", b =>
                {
                    b.HasOne("Domain.Event.Event", null)
                        .WithMany("Participants")
                        .HasForeignKey("EventId");

                    b.HasOne("Domain.Event.ParticipantType", "ParticipantType")
                        .WithMany("Participants")
                        .HasForeignKey("ParticipantTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Person", "Person")
                        .WithMany("Participants")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Track_sets.Set", b =>
                {
                    b.HasOne("Domain.Event.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Track_sets.SetTrack", b =>
                {
                    b.HasOne("Domain.Track_sets.Set", "Set")
                        .WithMany("SetTracks")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Track_sets.Track", "Track")
                        .WithMany("SetTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Track_sets.TrackPayRight", b =>
                {
                    b.HasOne("Domain.Person", "Person")
                        .WithMany("TrackPayRights")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Track_sets.Track", "Track")
                        .WithMany("TrackPayRights")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Venue.Equipment", b =>
                {
                    b.HasOne("Domain.Person", "Lender")
                        .WithMany()
                        .HasForeignKey("LenderPersonId");
                });

            modelBuilder.Entity("Domain.Venue.VenueEquipment", b =>
                {
                    b.HasOne("Domain.Venue.Equipment", "Equipment")
                        .WithMany("VenueEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Venue.Venue", "Venue")
                        .WithMany("VenueEquipments")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
